### ISSUE TITLE
Exits before authentication is complete?

### ISSUE THREAD

**Issue by andrewdunndev** [GioF71/yams-docker#21]
```
[tune@muckle mpd]$ podman run --pod=upmpd --privileged --replace --name=yams --env MPD_HOST=localhost --volume ~/mpd/yams:/data giof71/yams:latest
CMD_LINE=[yams --keep-alive --no-daemon -m localhost]
User mode enabled
Setting default value for PUID: [1000]
Setting default value for PGID: [1000]
group yams-group does not exist, creating...
user yams-user does not exist, creating...
uid=1000(yams-user) gid=1000(yams-group) groups=1000(yams-group)
user yams-user created.
Created yams-user (group: yams-group)
yams-user:x:1000:1000::/home/yams-user:/bin/bash
Creating home directory ...
Setting ownership ...
Setting home directory ...
yams-user:x:1000:1000::/data:/bin/bash
Executing [yams --keep-alive --no-daemon -m localhost --session-file-path /data/.config/yams/.lastfm_session]...
2024-04-18 15:30:57,461 - yams - INFO - Config found, reading from config at /data/.config/yams/yams.yml...
2024-04-18 15:30:57,461 - yams - INFO - Writing log to file: /data/.config/yams/yams.log
2024-04-18 15:30:57,461 - yams - INFO - Starting up YAMS v0.7.3
2024-04-18 15:30:57,461 - yams - ERROR - Couldn't read session file: [Errno 2] No such file or directory: '/data/.config/yams/.lastfm_session'
2024-04-18 15:30:57,461 - yams - INFO - Attempting new authentication...
2024-04-18 15:30:57,501 - yams - INFO - Token received, navigate to http://www.last.fm/api/auth/?api_key=293ef0836603c5c8023ba86eb413794b&token=tvb5OUdkzxyHasnO5hB6gPt7nY6EM1lE to authenticate...
Press Enter after you've granted scrobble.py permission to access your account...Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yams/scrobble.py", line 941, in find_session
    with open(session_file_path) as session_f_stream:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/.config/yams/.lastfm_session'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yams", line 5, in <module>
    from yams.__main__ import main
  File "/usr/local/lib/python3.11/site-packages/yams/__main__.py", line 3, in <module>
    cli_run()
  File "/usr/local/lib/python3.11/site-packages/yams/scrobble.py", line 1062, in cli_run
    user_name, session = find_session(
                         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yams/scrobble.py", line 966, in find_session
    session_info = authenticate(token, base_url, api_key, api_secret)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yams/scrobble.py", line 214, in authenticate
    input(
EOFError: EOF when reading a line
```

Do I need to pass an argument to tell it to wait until I click the link?

**Comment by GioF71** [comment]
Hello, this application cannot be started in one shot with docker (and probably with podman) if authentication data is not already available.
What I usually do, and should be in the readme, is running the image first with a docker-compose run command, which will enable to accept the "ENTER" keyboard press after you navigate to the suggested url.

So assuming the service is named yams, just run:

docker run yams

you will be presented with an url. Visit and authorize. Then press enter on the console as requested.
There should be some feedback saying everything should be ok. 
Then stop the container with CTRL-C.
Start the container as normal using 

docker-compose up -d

Of course this will work if you have mapped the volumes (like you are doing in your command).

Let me know if this works. If so, please have a look at the readme and see if this is not clear and/or how the documentation should be improved.

**Comment by GioF71** [comment]
You docker run command should do, you probably just need to run with -it the first time. Doing so the app will wait for input after you authorize the app on last.fm

**Comment by andrewdunndev** [comment]
The readme is clear on this, however because it's docker specific I didn't know what the analog for running interactively should be. Indeed `-it` does work. I was trying to run without the `--detach` command before and it was just exiting (as shown above), this is what worked for me:

> podman run -it --pod=upmpd --replace --name=yams --env MPD_HOST=localhost --volume ~/mpd/yams:/data giof71/yams:latest

Also it is scrobbling just fine!

**Comment by GioF71** [comment]
Remember to star the repo if you like the work :-)
